default: &default

development:
  adapter: postgresql
  database: sweater_weather_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sweater_weather_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sweater_weather_production
  pool: 5
  timeout: 5000
